name: Collect data daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  audit:
    name: Scrap data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Building
        run: yarn install --production
      - name: Scrap data
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          node ./crawler.js https://www.oryxspioenkop.com/2022/02/attack-on-europe-documenting-equipment.html
          node ./crawler.js https://www.oryxspioenkop.com/2022/02/attack-on-europe-documenting-ukrainian.html
